// Bundles /maps/<side>-<face>.tmj (side: out|in, face: 1-6) into
// shared/src/maps/generated.ts so both the server and the client can load them.
// Run with `npm run maps` after saving a map in Tiled, then commit the result.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const maps = {};
for (const side of ['out', 'in']) {
  for (let face = 1; face <= 6; face++) {
    const file = `${root}maps/${side}-${face}.tmj`;
    if (existsSync(file)) maps[`${side}-${face}`] = JSON.parse(readFileSync(file, 'utf8'));
  }
}
const body =
  '// GENERATED by `npm run maps` from /maps/<side>-<face>.tmj. Do not edit by hand.\n' +
  `export const TMJ_MAPS: Record<string, unknown> = ${JSON.stringify(maps, null, 2)};\n`;
writeFileSync(`${root}shared/src/maps/generated.ts`, body);
console.log(`maps: bundled ${Object.keys(maps).length} Tiled map(s): ${Object.keys(maps).join(', ') || 'none'}`);
